CREATE TABLE "COMU_DemarcacionMarina" 
( "ID_DEMARCACION" NUMBER(10) NOT NULL, 
	"ID_REGION" NUMBER(10) NULL, 
	"NOMBRE_RBIOGEOGRAFICA" VARCHAR2(255) NULL, 
	"REGION_CLASSIFICATION_VALUE" VARCHAR2(255) NULL, 
	"DEMARCACION_MARINA" VARCHAR2(50) NULL, 
	"ABREVIATURA_DMARINA" VARCHAR2(50) NULL,
	CONSTRAINT "PK_COMU_DemarcacionMarina" PRIMARY KEY ("ID_DEMARCACION")
) 
;
  /*Insert "COMU_DemarcacionMarina"*/
  
Insert into "COMU_DemarcacionMarina" 
   (ID_DEMARCACION,ID_REGION,NOMBRE_RBIOGEOGRAFICA,REGION_CLASSIFICATION_VALUE,DEMARCACION_MARINA,ABREVIATURA_DMARINA) 
 Values 
   (1,5,'Marina Atlántica','MATL','Nortatlántica','D.NOR');
Insert into "COMU_DemarcacionMarina" 
   (ID_DEMARCACION,ID_REGION,NOMBRE_RBIOGEOGRAFICA,REGION_CLASSIFICATION_VALUE,DEMARCACION_MARINA,ABREVIATURA_DMARINA) 
 Values 
   (2,5,'Marina Atlántica','MATL','Sudatlántica','D.SUD');
Insert into "COMU_DemarcacionMarina" 
   (ID_DEMARCACION,ID_REGION,NOMBRE_RBIOGEOGRAFICA,REGION_CLASSIFICATION_VALUE,DEMARCACION_MARINA,ABREVIATURA_DMARINA) 
 Values 
   (3,6,'Marina Mediterránea','MMED','Estrecho-Alboran','D.ESAL');
Insert into "COMU_DemarcacionMarina" 
   (ID_DEMARCACION,ID_REGION,NOMBRE_RBIOGEOGRAFICA,REGION_CLASSIFICATION_VALUE,DEMARCACION_MARINA,ABREVIATURA_DMARINA) 
 Values 
   (4,6,'Marina Mediterránea','MMED','Levantino-Balear','D.LEBA');
Insert into "COMU_DemarcacionMarina" 
   (ID_DEMARCACION,ID_REGION,NOMBRE_RBIOGEOGRAFICA,REGION_CLASSIFICATION_VALUE,DEMARCACION_MARINA,ABREVIATURA_DMARINA) 
 Values 
   (5,7,'Marina Macaronésica','MMAC','Canarias','D.CAN');
