CREATE TABLE "LC_ESPECIEINTCOMUNIT_ZEC_ANEXO" 
(	"TAXONID" NUMBER(10,0) NOT NULL,
   CONSTRAINT "LC_ESPECIEINTCOMUNIT_ZEC_A_PK" PRIMARY KEY ("TAXONID")
)
;
   
   /*Insert "LC_ESPECIEINTCOMUNIT_ZEC_ANEXO"*/
   
 