CREATE TABLE "LC_IFN_TRATMEJORASUELO" 
(	"ID_TRATMEJSUELO" VARCHAR2(1) NOT NULL, 
	"DS_TRATMEJSUELO" VARCHAR2(30) NULL,
	CONSTRAINT "PK_LC_IFN_TRATMEJORASUELO" PRIMARY KEY ("ID_TRATMEJSUELO")
)
;

	/*Insert "LC_IFN_TRATMEJORASUELO"*/
	
Insert into LC_IFN_TRATMEJORASUELO 
   (ID_TRATMEJSUELO,DS_TRATMEJSUELO) 
 values 
   ('0','No se observan');
Insert into LC_IFN_TRATMEJORASUELO 
   (ID_TRATMEJSUELO,DS_TRATMEJSUELO) 
 values 
   ('1','Ahoyados manuales');
Insert into LC_IFN_TRATMEJORASUELO 
   (ID_TRATMEJSUELO,DS_TRATMEJSUELO) 
 values 
   ('2','Ahoyados mecanizados');
Insert into LC_IFN_TRATMEJORASUELO 
   (ID_TRATMEJSUELO,DS_TRATMEJSUELO) 
 values 
   ('3','Subsolados');
Insert into LC_IFN_TRATMEJORASUELO 
   (ID_TRATMEJSUELO,DS_TRATMEJSUELO) 
 values 
   ('4','Acaballonados');
Insert into LC_IFN_TRATMEJORASUELO 
   (ID_TRATMEJSUELO,DS_TRATMEJSUELO) 
 values 
   ('5','Aterrazados');
Insert into LC_IFN_TRATMEJORASUELO 
   (ID_TRATMEJSUELO,DS_TRATMEJSUELO) 
 values 
   ('6','No se identifican');
Insert into LC_IFN_TRATMEJORASUELO 
   (ID_TRATMEJSUELO,DS_TRATMEJSUELO) 
 values 
   ('9','Otros');
	
	