CREATE TABLE "LC_INES_NIVELEROSIVO" 
(	"CD_NE" NUMBER(10,0) NOT NULL, 
	"NM_NE" VARCHAR2(255) NULL, 
	"NB_NE" VARCHAR2(255) NULL,
	CONSTRAINT "PK_LC_INES_NIVELEROSIVO" PRIMARY KEY ("CD_NE")
)
;

	/*Insert "LC_IFN_UDG"*/
	
