CREATE TABLE "LC_INES_RIESGO_EROSEOLICA" 
(	"ID_RIESGEROSEOL" NUMBER(1,0) NOT NULL, 
	"DS_RIESGEROSEOL" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_INES_RIESGO_EROSEOLICA" PRIMARY KEY ("ID_RIESGEROSEOL")
)
;

	/*Insert "LC_INES_RIESGO_EROSEOLICA"*/