 CREATE TABLE "LC_IFN_FIABILIDADEDAD" 
(	"ID_FIABILEDAD" NUMBER(10,0) NOT NULL, 
	"NB_FIABILEDAD" VARCHAR2(255) NULL,
	CONSTRAINT "PK_LC_IFN_FIABILIDADEDAD" PRIMARY KEY "ID_FIABILEDAD"	
)
;
	/*Insert "LC_IFN_FIABILIDADEDAD"*/

Insert into LC_IFN_FIABILIDADEDAD 
   (ID_FIABILEDAD,NB_FIABILEDAD) 
 values 
   ('1','Dudosa');
Insert into LC_IFN_FIABILIDADEDAD 
   (ID_FIABILEDAD,NB_FIABILEDAD) 
 values 
   ('2','Baja');
Insert into LC_IFN_FIABILIDADEDAD 
   (ID_FIABILEDAD,NB_FIABILEDAD) 
 values 
   ('3','Media');
Insert into LC_IFN_FIABILIDADEDAD 
   (ID_FIABILEDAD,NB_FIABILEDAD) 
 values 
   ('4','Alta');