CREATE TABLE "LC_IFN_UDGEOSTCRUZTENERIFE" 
(	"ID_UDGEOTEN" NUMBER (1) NOT NULL, 
	"NB_UDGEOTEN" VARCHAR2(15) NULL,
	CONSTRAINT "PK_LC_IFN_UDGEOSTCRUZTENERIFE" PRIMARY KEY ("ID_UDGEOTEN")
)
;

	/*Insert "LC_IFN_UDGEOSTCRUZTENERIFE"*/
	
Insert into LC_IFN_UDGEOSTCRUZTENERIFE 
   (ID_UDGEOTEN,NB_UDGEOTEN) 
 values 
   ('1','Tenerife');
Insert into LC_IFN_UDGEOSTCRUZTENERIFE 
   (ID_UDGEOTEN,NB_UDGEOTEN) 
 values 
   ('2','La Gomera');
Insert into LC_IFN_UDGEOSTCRUZTENERIFE 
   (ID_UDGEOTEN,NB_UDGEOTEN) 
 values 
   ('3','La Palma');
Insert into LC_IFN_UDGEOSTCRUZTENERIFE 
   (ID_UDGEOTEN,NB_UDGEOTEN) 
 values 
   ('4','El Hierro');