CREATE TABLE "LC_IFN_IMPORTANCIADANIO" 
(	"ID_IMPORTDANIO" NUMBER(1) NOT NULL, 
	"NB_IMPORTDANIO" VARCHAR2(20) NULL,
	CONSTRAINT "PK_LC_IFN_IMPORTANCIADANIO" PRIMARY KEY ("ID_IMPORTDANIO")
)
;

	/*Insert "LC_IFN_IMPORTANCIADANIO"*/
	
Insert into LC_IFN_IMPORTANCIADANIO 
   (ID_IMPORTDANIO,NB_IMPORTDANIO) 
 values 
   ('1','Pequeña');
Insert into LC_IFN_IMPORTANCIADANIO 
   (ID_IMPORTDANIO,NB_IMPORTDANIO) 
 values 
   ('2','Mediana');
Insert into LC_IFN_IMPORTANCIADANIO 
   (ID_IMPORTDANIO,NB_IMPORTDANIO) 
 values 
   ('3','Grande');