CREATE TABLE "LC_IFN_UDGEOLASPALMAS" 
(	"ID_UDGEOPAL" NUMBER (1) NOT NULL, 
	"NB_UDGEOPAL" VARCHAR2(15) NULL,
	CONSTRAINT "PK_LC_IFN_UDGEOLASPALMAS" PRIMARY KEY ("ID_UDGEOPAL")	
)
;

	/*Insert "LC_IFN_UDGEOLASPALMAS"*/
	
Insert into LC_IFN_UDGEOLASPALMAS 
   (ID_UDGEOPAL,NB_UDGEOPAL) 
 values 
   ('1','Gran Canaria');
Insert into LC_IFN_UDGEOLASPALMAS 
   (ID_UDGEOPAL,NB_UDGEOPAL) 
 values 
   ('2','Fuerteventura');
Insert into LC_IFN_UDGEOLASPALMAS 
   (ID_UDGEOPAL,NB_UDGEOPAL) 
 values 
   ('3','Lanzarote');