 CREATE TABLE "LC_IELIG_DIFICULTADITINER" 
(	"CD_DIFICULTAD" NUMBER(10,0) NOT NULL, 
	"DS_DIFICULTAD" VARCHAR2(255) NULL,
	CONSTRAINT "PK_LC_IELIG_DIFICULTADITINER" PRIMARY KEY ("CD_DIFICULTAD")
)
;

	/*Insert "LC_IELIG_DIFICULTADITINER"*/

	