CREATE TABLE "LC_IP_SUBTIPO" 
(	"ID_SUBTIPO" VARCHAR2(4) NOT NULL, 
	"DS_SUBTIPO" VARCHAR2(200) NULL,
	CONSTRAINT "LC_IP_SUBTIPO_PK" PRIMARY KEY ("ID_SUBTIPO")	
)
;

/*Insert "LC_IP_SUBTIPO"*/

Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S1','MACIZOS GALAICO LEONESES AL OESTE Y NOROESTE DEL BIERZO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S10','MACIZO DE GREDOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S100','CORREDORES IBERICOS CENTRALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S101','CORREDORES DE ALBACETE Y DEL OESTE DE VALENCIA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S102','CORREDORES IBERICO-LEVANTINOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S103','VALLES Y CORREDORES SEMIARIDOS DE ALMERIA, MURCIA Y EL SUR DE JAEN');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S104','VALLES DEL SUR DE SIERRA NEVADA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S105','CORREDORES OLIVAREROS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S106','ADEHESADAS SOBRE GRANITOS Y ESQUISTOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S107','ADEHESADAS SOBRE ESQUISTOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S108','INCIDIDAS DEL BORDE NORTE DE SIERRA MORENA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S109','ADEHESADAS SOBRE GRANITOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S11','ALTAS SIERRAS ORIENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S110','PIEDEMONTES DEL SISTEMA CENTRAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S111','RAMPA CRISTALINA DE TOLEDO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S112','CAMPIÑAS DEL NORTE DEL DUERO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S113','CAMPIÑAS DEL SUR DEL DUERO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S114','CAMPIÑAS SEGOVIANAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S115','CAMPIÑAS DEL SUR DE BURGOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S116','CAMPIÑAS Y ALTOS CAMPOS SORIANOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S117','EXTREMEÑAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S118','DE LA FOSA DEL TAJO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S119','MANCHEGAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S12','MACIZOS DEL NORTE DEL SISTEMA IBERICO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S120','CAMPIÑAS OLIVARERAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S121','CAMPIÑAS CEREALISTAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S122','CAMPIÑAS DE VIÑEDO Y OLIVAR');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S123','VEGAS Y REGADIOS RIOJANOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S124','VEGAS DEL JALON Y DEL SOMONTANO IBERICO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S125','PEQUEÑOS REGADIOS DEL CENTRO DE LA DEPRESION DEL EBRO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S126','VEGAS DE LA RIBERA DEL EBRO EN NAVARRA, ZARAGOZA Y TARRAGONA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S127','VEGAS DEL GALLEGO Y DEL HUERVA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S128','REGADIOS DE LOS MONEGROS Y LAS BARDENAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S129','REGADIOS Y VEGAS DEL CINCA, LA NOGUERA Y EL SEGRE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S13','MACIZOS DEL NORTE DEL MONCAYO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S130','VEGAS Y REGADIOS DEL GUADIANA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S131','VEGAS Y REGADIOS CACEREÑOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S132','VEGAS DEL TAJO Y JARAMA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S133','LLANOS CENTRALES DE SEGOVIA, VALLADOLID Y AVILA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S134','LLANOS ORIENTALES SORIANOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S135','LLANO NOROCCIDENTAL LEONES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S136','LLANOS Y GLACIS NAVARROS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S137','SOMONTANOS DEL PIRINEO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S138','LLANOS Y GLACIS DE LA DEPRESION CENTRAL CATALANA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S139','LLANOS Y GLACIS DEL CENTRO DE LA DEPRESION DEL EBRO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S14','MACIZO TUROLENSES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S140','GLACIS Y LLANOS DEL SOMONTANO IBERICO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S141','LLANOS ENDORREICOS DE GALLO CANTA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S142','LLANOS MANCHEGOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S143','LLANOS ENDORREICOS Y LAGUNAS MANCHEGOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S144','LLANOS TOLEDANOS EN EL VALLE MEDIO DEL TAJO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S145','LLANOS MARGO- YESIFEROS DE LA SAGRA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S146','LLANOS MURCIANO-ALBACETEÐOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S147','MEDITERRANEOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S148','ATLANTICOS Y DEL CAMPO DE GIBRALTAR');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S149','VALLES ALTOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S15','MACIZO DE SIERRA NEVADA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S150','VALLES MEDIOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S151','PARAMOS ALCARREÑOS Y MANCHEGOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S152','PARAMERAS DEL CAMPO DE MONTIEL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S153','PARAMOS DEL INTERIOR VALENCIANO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S154','DE CUENCA Y GUADALAJARA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S155','MUELAS DE CASTELLÓ, TERUEL Y NORTE DE VALENCIA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S156','MUELAS DE ALBACETE Y VALENCIA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S157','CASTELLANAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S158','ONUBENSES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S159','SEPTENTRIONALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S16','MACIZOS MONTAÑOSOS ORIENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S160','GOLFO ARTABRO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S161','COSTA DA MORTE Y CORCUBION');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S162','DELTA DEL EBRO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S163','PEQUEÑOS DELTAS MEDITERRANEOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S164','MARISMAS Y COMPLEJOS LITORALES ENTRE CADIZ Y TARIFA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S165','MARISMAS DEL GUADALQUIVIR');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S166','MARISMAS Y COMPLEJOS LITORALES DEL CENTRO Y OESTE DE HUELVA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S167','MONTES Y TURONS DE MENORCA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S168','PEQUEÑAS SIERRAS Y MONTES DE MALLORCA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S169','SIERRAS Y MOLA DE LAS PITIUSAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S17','MACIZO MONTAÑOSO OCCIDENTAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S170','RAMPAS DEL TEIDE-LAS CAÑADAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S171','RAMPAS Y VALLESINTERCOLINARES DE LA DORSAL DE PEDRO GIL (BARLOVENTO)');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S172','RAMPAS Y VALLESINTERCOLINARES DE LA DORSAL DE PEDRO GIL (SOTAVENTO)');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S173','VERTIENTES ALTAS DE LA PALMA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S174','VERTIENTES BAJAS Y ESTRECHAS DEL SUR DE LA PALMA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S175','VERTIENTES Y BARRANCOS DEL NOROESTE DE LA PALMA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S176','BARRANCO DE LA CALDERA DE TABURIENTE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S177','BARRANCOS, VALLES Y LOMOS DEL BARLOVENTO DE GRAN CANARIA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S178','BARRANCOS, VALLES Y LOMOS DEL SOTAVENTO DE GRAN CANARIA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S179','VERTIENTES ESCARPADAS DEL HIERRO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S18','SIERRAS SUBBETICAS MEDITERRANEO - OCEANICAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S180','RAMPAS DEL HIERRO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S181','VERTIENTES DEL NORTE DE LA ISLA DEL HIERRO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S182','BARRANCOS Y RAMPAS NOROCCIDENTALES DE LA GOMERA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S183','CUCHILLOS Y VALLES DE FUERTEVENTURA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S184','MONTAÑAS Y SUAVES VERTIENTES DE LANZAROTE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S185','LLANOS LITORALES Y MALPAISES DE  LANZAROTE Y FUERTEVENTURA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S186','LLANOS Y SUAVES RAMPAS LITORALES DE LA PALMA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S187','SUAVES RAMPAS LITORALES E ISLAS BAJAS DEL NORTEDE TENERIFE Y GRAN CANARIA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S188','LLANOS Y RAMPAS LITORALES DEL SOTAVENTO DE TENERIFE Y GRAN CANARIA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S189','RAMPAS LITORALES E ISLA BAJA DEL HIERRO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S19','MACIZOS Y SIERRAS PREBÉTICOS Y SUBBÉTICOS MEDITERRÁNEO-CONTINENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S190','VALLES  GOMEROS DE BARLOVENTO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S191','VALLES GOMEROS DE SOTAVENTO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S192','MACIZOS ANTIGUOS DE LAS ISLAS DE TENERIFE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S193','MACIZO CENTRO - OCCIDENTAL DE FUERTEVENTURA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S194','MACIZOS ANTIGUOS DE LANZAROTE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S2','MACIZOS LEONESES AL NORTE Y NORESTE DEL BIERZO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S20','SIERRAS GALLEGAS ORIENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S21','SIERRAS GALLEGAS SEPTENTRIONALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S22','SIERRAS OCCIDENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S23','SIERRAS GALLEGAS EN LA FRONTERA PORTUGUESA Y EL SURESTE ORENSANO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S24','MONTES DEL SURESTE DE PONTEVEDRA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S25','TIERRAS ALTAS GALAICO-ZAMORANAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S26','SIERRAS ZAMORANAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S27','MONTES DE LEON');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S28','SIERRAS DEL NORTE DE BURGOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S29','PARAMOS Y LORAS DE BURGOSY PALENCIA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S3','MACIZOS AL SUR DEL BIERZO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S30','MONTES DE LA DIVISORIA CANTABRICA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S31','SIERRAS VASCAS Y NAVARRAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S32','ALTAS SIERRAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S33','SIERRAS MEDIAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S34','SIERRAS DE LA CADENA TRANSVERSAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S35','SIERRAS PRELITORALES AL NORESTE DEL MONTSENY');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S36','SIERRAS PRELITORALES DEL VALLES Y EL BAIX LLOBREGAT');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S37','SIERRAS DEL PENEDES -A NOIA - ALT CAMP');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S38','SIERRAS SUROCCIDENTALES DE LA CADENA PRELITORAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S39','SIERRAS DEL PORTS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S4','MACIZO ORIENTAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S40','SIERRAS DEL MAESTRAZGO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S41','SIERRAS DEL NORTE DEL SISTEMA IBERICO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S42','SIERRAS ZARAGONAS Y SORIANAS DEL SISTEMA IBERICO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S43','SIERRAS DEL BAJO ARAGÓN, CUENCAS MINERASY NORTE DE CASTELLÓ');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S44','SIERRAS DE MOLINA Y MENERA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S45','ALTAS SIERRAS AL OESTE DE TERUEL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S46','PEQUEÑAS SIERRAS OCCIDENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S47','SERRANIAS DEL ENTORNO DE GUDAR');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S48','SIERRAS DEL SUR DE CASTELLÓ');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S49','SIERRAS VALENCIANAS DEL SISTEMA IBERICO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S5','PICOS DE EUROPA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S50','SIERRAS CENTRALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S51','SIERRAS ORIENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S52','ANDALUZAS OCCIDENTALES Y CENTRALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S53','ANDALUZAS ORIENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S54','LEVANTINAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S55','PEQUEÑAS SIERRAS Y CERROS DEL SUR DE ALBACETE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S56','SIERRAS DEL ESCUDO DE CABUERNIGA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S57','SIERRAS DEL ORIENTE ASTURIANO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S58','SIERRAS DEL OCCIDENTE ASTURIANO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S59','MONTES LITERALES DE LA MARIÑA LUCENSE Y LOS BERGANTIÑOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S6','MACIZOS CENTRALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S60','PEQUEÑAS SIERRAS DEL SUR PONTEVEDRA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S61','SIERRAS DEL PIRINEO Y LA CORDILLERA TRANSVERSAL CATALANA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S62','SIERRAS DE LA CORDILLERA COSTERO CATALANA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S63','SIERRAS DEL ARCO VALENCIANO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S64','SIERRAS ANDALUZAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S65','SIERRAS LEVANTINAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S66','SIERRAS Y VALLES DE LA VERTIENTE MERIDIONAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S67','SIERRAS Y VALLES DE LA VERTIENTE SEPTENTRIONAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S68','SIERRAS Y VALLES OCCIDENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S69','SIERRAS Y VALLES CENTRALES Y ORIENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S7','MACIZOS OCCIDENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S70','ANDALUCES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S71','LEVANTINOS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S72','DEL NORTE DE HUELVA Y SEVILLA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S73','DE CORDOBA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S74','DEL SUR DE CIUDAD REAL Y DE JAEN');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S75','MONTES DEL INTERFLUVIO ULLA- MIÑO EN LA MESETA DE LUGO');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S76','MONTES MERIDIONALES AL SUR DEL ULLA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S77','MONTES AL NORTE DEL TAMBRE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S78','MONTES AL SUR DEL TAMBRE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S79','OCCIDENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S8','MACIZOS ORIENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S80','ORIENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S81','DEPRESIONES ZAMORANO-LEONESAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S82','DEPRESIONES ORENSANAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S83','DEPRESIONES LUCENSES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S84','DEPRESIONES DEL CORREDOR PRELITORAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S85','DEPRESIONES NAVARRAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S86','DEPRESION VASCA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S87','DEPRESIONES DE LA CORDILLERA CANTABRICA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S88','DEPRESION CENTRAL ASTURIANA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S89','CONCAS Y LLANOS DE LA DEPRESION CENTRAL CATALANA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S9','ALTAS SIERRAS OCCIDENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S90','LLANOS ALOMADOS GERUNDENSES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S91','VALLES Y LLANOS ALOMADOS DE LA DEPRESION PRELITORAL');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S92','DEPRESIONES PIRENAICAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S93','FOSAS CACEREÑAS U OCCIDENTALES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S94','FOSAS ABULENSES');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S95','FOSA DEL BAJO ALBERCHE');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S96','FOSAS DEL GUADARRAMA');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S97','ANDALUZAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S98','ALICANTINAS');
Insert into LC_IP_SUBTIPO 
   (ID_SUBTIPO,DS_SUBTIPO) 
 values 
   ('S99','DEPRESION DE CALATAYUD-TERUEL Y VALLE  DEL ALFAMBRA');