CREATE TABLE "LC_IFN_TIPOSESTRUCT2" 
(	"ID_TIPOESTRUCT_2" NUMBER(1,0) NOT NULL, 
	"DS_TIPOESTRUCT_2" VARCHAR2(50) NULL, 
	"ID_TIPOESTRUCT_1" NUMBER(1,0) NOT NULL,
	CONSTRAINT "PK_LC_IFN_TIPOSESTRUCT2" PRIMARY KEY ("ID_TIPOESTRUCT_2", "ID_TIPOESTRUCT_1")
)
;
	/*Insert "LC_IFN_TIPOSESTRUCT2"*/
	
