CREATE TABLE "LC_IELIG_TRAMO" 
(	"ID_LIG" NUMBER(8) NOT NULL, 
	"NB_LITOLOGIA" VARCHAR2(50) NULL, 
	"NM_POTENCIA" NUMBER(6,2) NULL,	
	"TC_EDAD" NUMBER(3,0),
	CONSTRAINT "PK_LC_IELIG_TRAMO" PRIMARY KEY ("ID_LIG")
)
;

	/*Insert "LC_IELIG_TRAMO"*/