CREATE TABLE "LC_IEBMBG_JB" 
("ID_JB" NUMBER(3) NOT NULL, 
	"NB_JB" VARCHAR2(250) NULL, 
	"DS_JB" VARCHAR2(10) NULL,
	CONSTRAINT "PK_LC_IEBMBG_JB" PRIMARY KEY ("ID_JB")
);

	/*Insert "LC_IEBMBG_JB"*/