 CREATE TABLE "LC_INES_UDHIDROLOGICA" 
(	"CD_UDHI" NUMBER(5,0) NOT NULL, 
	"NB_UDHI" VARCHAR2(50) NULL, 
	"DESDE_UDHI" VARCHAR2(50) NULL, 
	"HASTA_UDHI" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_INES_UDHIDROLOGICA" PRIMARY KEY ("CD_UDHI")
)
;

	/*Insert "LC_INES_UDHIDROLOGICA"*/
	
