CREATE TABLE "LC_INES_RIESGO_EROSCAUCES" 
(	"ID_RIESGEROSCAUC" NUMBER(1,0) NOT NULL, 
	"DS_RIESGEROSCAUC" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_INES_RIESGO_EROSCAUCES" PRIMARY KEY ("ID_RIESGEROSCAUC")
)
;

	/*Insert "LC_INES_RIESGO_EROSCAUCES"*/
	
