CREATE TABLE "LC_IFN_TRATMEJORAVUELO" 
(	"ID_TRATMEJVUELO" VARCHAR2(1) NOT NULL, 
	"DS_TRATMEJVUELO" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_IFN_TRATMEJORAVUELO" PRIMARY KEY ("ID_TRATMEJVUELO")
)
;

	/*Insert "LC_IFN_TRATMEJORAVUELO"*/
	
Insert into LC_IFN_TRATMEJORAVUELO 
   (ID_TRATMEJVUELO,DS_TRATMEJVUELO) 
 values 
   ('0','No se observan');
Insert into LC_IFN_TRATMEJORAVUELO 
   (ID_TRATMEJVUELO,DS_TRATMEJVUELO) 
 values 
   ('1','Limpias (siegas, rozas, desbroces, etc.)');
Insert into LC_IFN_TRATMEJORAVUELO 
   (ID_TRATMEJVUELO,DS_TRATMEJVUELO) 
 values 
   ('2','Clareos');
Insert into LC_IFN_TRATMEJORAVUELO 
   (ID_TRATMEJVUELO,DS_TRATMEJVUELO) 
 values 
   ('3','Claras');
Insert into LC_IFN_TRATMEJORAVUELO 
   (ID_TRATMEJVUELO,DS_TRATMEJVUELO) 
 values 
   ('4','Podas');
Insert into LC_IFN_TRATMEJORAVUELO 
   (ID_TRATMEJVUELO,DS_TRATMEJVUELO) 
 values 
   ('9','Otros');