CREATE TABLE "LC_IELIG_ZONAGEODE" 
(	"CD_GEODE" NUMBER(4,0) NOT NULL, 
	"NB_GEODE" VARCHAR2(125) NULL,
	CONSTRAINT "PK_LC_IELIG_ZONAGEODE" PRIMARY KEY ("CD_GEODE")
)
;

	/*Insert "LC_IELIG_ZONAGEODE"*/