CREATE TABLE "LC_IP_ASOCIACION" 
(	"CD_ASOCIACION" VARCHAR2(4) NOT NULL, 
	"DS_ASOCIACION" VARCHAR2(200) NULL,
	CONSTRAINT "PK_LC_IP_ASOCIACION" PRIMARY KEY ("CD_ASOCIACION")
)
;

	/*Insert "LC_IP_ASOCIACION"*/
	

Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A1','MACIZOS MONTAÑOSOS SEPTENTRIONALES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A10','CUENCAS, HOYAS Y DEPRESIONES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A11','CORREDORES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A12','PENILLANURAS Y PIEDEMONTES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A13','CAMPIÑAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A14','VEGAS Y RIBERAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A15','LLANOS INTERIORES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A16','LLANOS LITORALES PENINSULARES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A17','VALLES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A18','PARAMOS Y MESAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A19','MUELAS Y PARAMERAS IBÉRICAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A2','MACIZOS MONTAÑOSOS DEL INTERIOR IBÉRICO');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A20','GARGANTAS, DESFILADEROS Y HOCES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A21','RÍAS, MARINAS Y RASAS CANTÁBRICO - ATLÁNTICAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A22','MARISMAS, DELTAS Y ARENALES MEDITERRÁNEOS Y SURATLÁNTICOS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A23','ISLAS MENORES E ISLOTES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A24','GRANDES CIUDADES Y SUS ÁREAS METROPOLITANAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A25','CIUDADES NORTEAFRICANAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A26','LLANOS Y BAHÍAS BALEÁRICOS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A27','SIERRAS BÉTICAS MALLORQUINAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A28','PEQUEÑAS SIERRAS, MONTES Y TURONS DE LAS BALEARES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A29','CUMBRES CANARIAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A3','MACIZOS MONTAÑOSOS DE LAS CORDILLERAS BÉTICAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A30','RAMPAS, ESCARPES, BARRANCOS Y VALLES CANARIOS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A31','LLANOS CANARIOS Y SUAVES RAMPAS LITORALES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A32','MACIZOS ANTIGUOS CANARIOS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A33','DORSALES Y CAMPOS DE LAVAS RECIENTES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A34','CIUDADES INSULARES CANARIAS Y SU PERIURBANO');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A4','SIERRAS Y MONTAÑAS ATLÁNTICAS Y SUBATLÁNTICAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A5','SIERRAS PIRENAICAS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A6','SIERRAS Y MONTAÑAS MEDITERRÁNEAS Y CONTINENTALES');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A7','SIERRAS, CERROS Y VALLES ANDALUCES, LEVANTINOS Y EXTREMEÑOS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A8','MONTES Y VALLES ATLÁNTICOS Y SUBATLÁNTICOS');
Insert into LC_IP_ASOCIACION 
   (CD_ASOCIACION,DS_ASOCIACION) 
 values 
   ('A9','CERROS, LOMAS Y LLANOS DEL NORTE DE SIERRA MORENA Y DEL BORDE SUBBÉTICO');