CREATE TABLE "LC_IFN_TIPOSESTRUCT3" 
(	"ID_TIPOESTRUCT_3" NUMBER(4,0), 
	"NB_TIPOESTRUCT_3" VARCHAR2(150), 
	"DS_TIPOESTRUCT_3" CLOB, 
	"FC_ALTA_MODIF_3" DATE, 
	"ID_TIPOESTRUCT_2" NUMBER(2,0),
	CONSTRAINT "LC_IFN_TIPOSESTRUCT3_PK" PRIMARY KEY ("ID_TIPOESTRUCT_3", "ID_TIPOESTRUCT_2")
)
;

	/*Insert "LC_IFN_TIPOSESTRUCT3"*/
	
