CREATE TABLE "LC_IFN_COMPESPECIFICA2" 
(	"ID_COMPESP2" VARCHAR2(2) NOT NULL, 
	"NB_COMPESP2" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_IFN_COMPESPECIFICA2" PRIMARY KEY ("ID_COMPESP2")
);
   
   /*Insert "LC_IFN_COMPESPECIFICA2"*/
   
Insert into LC_IFN_COMPESPECIFICA2 
   (ID_COMPESP2,NB_COMPESP2) 
 values 
   ('DO','Masas con especie dominante');
Insert into LC_IFN_COMPESPECIFICA2 
   (ID_COMPESP2,NB_COMPESP2) 
 values 
   ('MX','Masas mixtas');