CREATE TABLE "LC_IP_TIPOPAISAJE" 
(	"CD_TIPOPAISAJE" NUMBER(4) NOT NULL, 
	"DS_TIPOPAISAJE" VARCHAR2(300) NULL, 
	"CD_ASOCIACION" VARCHAR2(4) NULL,
	CONSTRAINT "PK_LC_IP_TIPOPAISAJE" PRIMARY KEY ("CD_TIPOPAISAJE")
)
;

	/*Insert "LC_IP_TIPOPAISAJE"*/
	
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('1','MACIZOS MONTAÑOSOS GALAICO-ASTURIANO-LEONESES','A1');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('2','MACIZOS MONTAÑOSOS CANTABRICOS','A1');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('3','MACIZOS MONTAÑOSOS PIRENAICOS','A1');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('4','MACIZOS MONTAÑOSOS CATALANES MEDITERRANEOS','A1');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('5','MACIZOS Y SIERRAS ALTAS DEL SISTEMA CENTRAL','A2');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('6','MACIZOS MONTAÑOSOS IBERICOS','A2');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('7','MACIZOS MONTAÑOSOS BETICOS','A3');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('8','MACIZOS MONTAÑOSOS Y ALTAS SIERRAS SUBBETICOS-PREBETICOS','A3');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('9','SIERRAS GALLEGAS Y DE LA DIVISORIA ASTUR-LEONESA','A4');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('10','TIERRAS ALTAS, MONTES Y SIERRAS GALAICO-ZAMORANO-LEONESAS','A4');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('11','SIERRAS Y PARAMERAS ORIENTALES DE LA CORDILLERA CANTABRICA Y DE LOS MONTES VASCOS Y NAVARROS','A4');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('12','SIERRAS PIRENAICAS','A5');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('13','SIERRAS PRELITORALES CATALANAS Y CASTELLONENSES','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('14','SIERRAS IBERICAS','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('15','SIERRAS DEL SISTEMA CENTRAL','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('16','SIERRAS BETICAS','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('17','SIERRAS DE LOS MONTES DE TOLEDO Y DE LAS VILLUERCAS','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('18','SIERRAS CUARCITICAS DE LA PENILLANURA EXTREMEÑA','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('19','SIERRAS MEDITERRANEAS CON VULCANISMO','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('20','SIERRAS LITORALES Y PRELITORALES CANTABRICO-ATLANTICAS','A4');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('21','SIERRAS LITORALES CATALANO-VALENCIANAS','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('22','SIERRAS LITORALES Y SUBLITORALES BETICAS','A6');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('23','SIERRAS Y VALLES DE LA CORDILLERA CANTABRICA','A4');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('24','SIERRAS Y VALLES PIRENAICOS','A5');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('25','SIERRAS CUARCÍTICAS Y VALLES EXTREMEÑOS','A7');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('26','SIERRAS Y VALLES BETICOS','A7');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('27','SIERRAS Y VALLES DE LA SIERRA MORENA','A7');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('28','MONTES GALLEGOS','A8');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('29','MONTES Y VALLES VASCOS, DEL CONDADO DE TREVIÑO Y DEL PIRINEO NAVARRO','A8');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('30','CERROS Y LLANOS DEL NORTE DE SIERRA MORENA','A9');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('31','CERROS Y LOMAS DEL BORDE SUBBETICO','A9');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('32','CUESTAS Y CHAOS DE LOS VALLES DEL MIÑO Y DEL ULLA','A8');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('33','CUESTAS DE LA DEPRESION CENTRAL CATALANA','A10');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('34','LADERAS Y VALLES DE LA SIERRA MORENA AL GUADALQUIVIR','A7');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('35','VERTIENTES, CERROS Y LOMAS DEL ANDÉVALO','A12');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('36','DEPRESIONES GALAICO-ZAMORANO-LEONESAS','A10');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('37','DEPRESIONES VASCAS, NAVARRAS Y DE LA CORDILLERA CANTABRICA','A10');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('38','DEPRESIONES Y CONCAS CATALANAS','A10');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('39','DEPRESIONES IBERICAS DEL CORREDOR SORIA-BURGOS','A10');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('40','FOSAS DEL SISTEMA CENTRAL Y SUS BORDES','A10');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('41','CUENCAS MURCIANAS','A10');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('42','HOYAS Y DEPRESIONES BETICO-ALICANTINAS','A10');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('43','CORREDORES CANTABRICO-PIRENAICOS','A11');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('44','CORREDORES CASTELLONENSES','A11');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('45','CORREDORES Y DEPRESIONES IBERICOS','A11');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('46','CORREDORES Y VALLES INTRAMONTAÑOSOS CASTELLANO-MANCHEGOS','A11');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('47','VALLES Y CORREDORES INTRAMONTAÑOSOS BETICOS','A11');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('48','PENILLANURAS SUROCCIDENTALES','A12');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('49','PENILLANURAS SALMANTINO-ZAMORANAS Y PIEDEMONTE DE LOS MONTES DE LEON','A12');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('50','PIEDEMONTES DEL SISTEMA CENTRAL Y DE LOS MONTES DE TOLEDO','A12');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('51','CAMPIÑAS DE LA MESETA NORTE','A13');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('52','CAMPIÑAS DE LA DEPRESION DEL EBRO','A13');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('53','CAMPIÑAS DE LA MESETA SUR','A13');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('54','CAMPIÑAS ANDALUZAS','A13');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('55','VEGAS DEL DUERO','A14');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('56','VEGAS Y RIEGOS DEL EBRO','A14');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('57','VEGAS DEL TAJO Y DEL GUADIANA','A14');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('58','VEGAS DEL SEGURA Y REGADIOS DE HELLIN Y TOBARRA','A14');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('59','VEGAS DEL GUADALQUIVIR, GENIL Y GUADALETE','A14');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('60','LLANOS CASTELLANOS','A15');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('61','LLANOS Y GLACIS DE LA DEPRESION DEL EBRO','A15');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('62','LLANOS DE LA MESETA MERIDIONAL Y SUS BORDES','A15');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('63','LLANOS INTERIORES ANDALUCES','A15');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('64','LLANOS Y GLACIS LITORALES Y PRELITORALES','A16');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('65','VALLES GALLEGOS','A17');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('66','VALLES INTRAMONTAÑOSOS CANTABROS','A17');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('67','VALLES INTRAMONTAÑOSOS ASTURIANOS','A17');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('68','VALLES INTRAMONTAÑOSOS PALENTINO-LEONESES','A17');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('69','VALLES PIRENAICOS','A17');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('70','VALLES INTRAMONTAÑOSOS RIOJANOS Y SORIANOS','A17');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('71','VALLES INDUSTRIALES VASCOS','A17');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('72','VALLES DEL NORTE DE BURGOS','A17');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('73','RIBERRA DEL EBRO ENTRE ALFORQUE Y MORA D''EBRE','A14');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('74','PARAMOS CALCAREOS CASTELLANO-LEONESES','A18');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('75','PARAMOS DETRITICOS CASTELLANO-LEONESES','A18');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('76','MESAS ARAGONESAS','A18');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('77','PARAMOS Y PARAMERAS DE LA MESETA MERIDIONAL','A18');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('78','PARAMOS DETRITICOS DE LA MESETA MERIDIONAL','A18');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('79','MUELAS IBERICAS','A19');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('80','PARAMERAS IBERICAS','A19');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('81','VALLES ENCAJADOS GALLEGOS','A20');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('82','DESFILADEROS CANTABRICOS','A20');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('83','CAÑONES Y DESFILADEROS DEL ALTO EBRO','A20');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('84','GARGANTAS Y VALLES EN LA FRONTERA PORTUGUESA','A20');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('85','HOCES Y GARGANTAS IBERICO-LEVANTINAS','A20');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('86','GRANDES CIUDADES Y AREAS METROPOLITANAS','A24');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('87','RIAS ALTAS, MONTES Y VALLES LITORALES GALLEGOS','A21');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('88','GRANDES RIAS GALLEGAS (RIAS BAJAS)','A21');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('89','RIAS Y BAHIAS CANTABRICO-ATLANTICAS','A21');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('90','MARINAS, MONTES Y VALLES DEL LITORAL CANTABRICO','A21');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('91','RASAS CANTABRICAS','A21');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('92','DELTAS Y LLANOS FLUVIALES ASOCIADOS','A22');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('93','COSTAS DUNARES DE DOÑANA','A22');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('94','MARIASMAS ANDALUZAS','A22');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('95','ISLAS MENORES E ISLOTES BALEARICOS','A23');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('96','LLANOS LITORALES DE MALLORCA','A26');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('97','LLANOS INTERIORES DE MALLORCA','A26');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('98','LLANOS DE MENORCA','A26');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('99','LLANOS DE LAS PITIUSAS','A26');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('100','BAHIAS DE MALLORCA','A26');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('101','SIERRAS BETICAS MALLORQUINAS','A27');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('102','PEQUEÑAS SIERRAS, MONTES Y TURONS DE LAS BALEARES','A28');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('103','CUMBRES CANARIAS','A29');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('104','RAMPAS, BARRANCOS Y VALLES CANARIOS','A30');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('105','LLANOS Y SUAVES RAMPAS LITORALES, ISLAS BAJAS CON O SIN VOLCANES','A31');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('106','VALLES DE LA GOMERA','A30');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('107','MACIZOS ANTIGUOS DE LAS ISLAS DE TENERIFE, FUERTEVENTURA Y LANZAROTE','A32');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('108','DORSALES Y CAMPOS DE LAVAS RECIENTES','A33');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('109','GRANDES ESCARPES CANARIOS','A30');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('110','LLANOS INTERIORES CANARIOS','A31');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('111','ARENALES Y JABLES CANARIOS','A31');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('112','CAPITALES CANARIAS Y SU PERIURBANO','A34');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('113','ISLAS MENORES DE CANARIAS','A23');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('114','OTRAS ISLAS E ISLOTES ATLANTICOS','A23');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('115','OTRAS ISLAS MEDITERRANEAS*','A23');
Insert into LC_IP_TIPOPAISAJE 
   (CD_TIPOPAISAJE,DS_TIPOPAISAJE,CD_ASOCIACION) 
 values 
   ('116','CIUDADES NORTEAFRICANAS*','A25');