CREATE TABLE "LC_INES_REGIMENPROPIEDAD" 
(	"ID_REGPROP" NUMBER(1,0) NOT NULL, 
	"DS_REGPROP" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_INES_REGIMENPROPIEDAD" PRIMARY KEY ("ID_REGPROP")
)
;

	/*Insert "LC_INES_REGIMENPROPIEDAD"*/
	

	
