CREATE TABLE "LC_INES_PENDIENTE" 
(	"ID_PEND" NUMBER(10,0) NOT NULL, 
	"NM_PEND" VARCHAR2(255) NULL,
	CONSTRAINT "PK_LC_INES_PENDIENTE" PRIMARY KEY ("ID_PEND")
)
;
	/*Insert "LC_INES_PENDIENTE"*/
	
