CREATE TABLE "LC_INES_POTENCIALIDADBASICA" 
(	"ID_PO" NUMBER(1,0) NOT NULL, 
	"NM_PO" VARCHAR2(20) NULL, 
	"DS_PO" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_INES_POTENCIALIDADBASIC" PRIMARY KEY ("ID_PO")
)
;

	/*Insert "LC_INES_POTENCIALIDADBASICA"*/
	

	
