CREATE TABLE "LC_INES_TIPOMOVIMIENTO" 
(	"ID_TIPOMOV" NUMBER(1,0) NOT NULL, 
	"DS_TIPOMOV" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_INES_TIPOMOVIMIENTO" PRIMARY KEY ("ID_TIPOMOV")
)
;

	/*Insert "LC_INES_TIPOMOVIMIENTO"*/
	
