CREATE TABLE "LC_IFN_TIPOSESTRUCT1" 
(	"ID_TIPOESTRUCT_1" NUMBER (1,0) NOT NULL, 
	"DS_TIPOESTRUCT_1" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_IFN_TIPOSESTRUCT1" PRIMARY KEY ("ID_TIPOESTRUCT_1")
)
;

	/*Insert "LC_IFN_TIPOSESTRUCT1"*/

Insert into LC_IFN_TIPOSESTRUCT1 
   (ID_TIPOESTRUCT_1,DS_TIPOESTRUCT_1) 
 values 
   ('1','SUPERFICIE FORESTAL');
Insert into LC_IFN_TIPOSESTRUCT1 
   (ID_TIPOESTRUCT_1,DS_TIPOESTRUCT_1) 
 values 
   ('2','ZONAS HÚMEDAS');
Insert into LC_IFN_TIPOSESTRUCT1 
   (ID_TIPOESTRUCT_1,DS_TIPOESTRUCT_1) 
 values 
   ('3','SUPERFICIES DE AGUA');
Insert into LC_IFN_TIPOSESTRUCT1 
   (ID_TIPOESTRUCT_1,DS_TIPOESTRUCT_1) 
 values 
   ('4','SUPERFICIES AGRÍCOLAS');
Insert into LC_IFN_TIPOSESTRUCT1 
   (ID_TIPOESTRUCT_1,DS_TIPOESTRUCT_1) 
 values 
   ('5','SUPERFICIES ARTIFICIALES');