CREATE TABLE "LC_IEBMBG_BAG" 
(	"ID_BAG" NUMBER(3) NOT NULL, 
	"NB_BAG" VARCHAR2(250) NULL, 
	"DS_BAG" VARCHAR2(10) NULL,
	CONSTRAINT "LC_IEBMBG_BAG_PK" PRIMARY KEY ("ID_BAG")
);

	/*Insert "LC_IEBMBG_BAG"*/
   
