CREATE TABLE "LC_IELIG_ESCALAVALORACION_01" 
(	"CD_VALORACION_01" NUMBER(1,0) NOT NULL, 
	"NB_VALORACION_01" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_IELIG_ESCALAVALORACION" PRIMARY KEY ("CD_VALORACION_01")
)
;
   
   /*Insert "LC_IELIG_ESCALAVALORACION_01"*/