CREATE TABLE "LC_IFN_PARAMETROSDENDRO" 
(	"ID_PARAMDENDRO" NUMBER (1,0) NOT NULL, 
	"DS_PARAMDENDRO" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_IFN_PARAMETROSDENDRO" PRIMARY KEY ("ID_PARAMDENDRO")
)
;

	/*Insert "LC_IFN_PARAMETROSDENDRO"*/
	
Insert into LC_IFN_PARAMETROSDENDRO 
   (ID_PARAMDENDRO,DS_PARAMDENDRO) 
 values 
   ('1','Vcc');
Insert into LC_IFN_PARAMETROSDENDRO 
   (ID_PARAMDENDRO,DS_PARAMDENDRO) 
 values 
   ('2','Vsc');
Insert into LC_IFN_PARAMETROSDENDRO 
   (ID_PARAMDENDRO,DS_PARAMDENDRO) 
 values 
   ('3','Iavc');
Insert into LC_IFN_PARAMETROSDENDRO 
   (ID_PARAMDENDRO,DS_PARAMDENDRO) 
 values 
   ('4','Vle');
