CREATE TABLE "LC_IEPFCMUP_PERTENENCIA" 
(	"ID_PERTENENCIA" NUMBER(10,0) NOT NULL, 
	"DS_PERTENENCIA" VARCHAR2(255) NULL,
	CONSTRAINT "LC_IEPFCMUP_PERTENENCIA_PK" PRIMARY KEY ("ID_PERTENENCIA")
);
   
   /*Insert "LC_IEPFCMUP_PERTENENCIA"*/
   
Insert into LC_IEPFCMUP_PERTENENCIA 
   (ID_PERTENENCIA,DS_PERTENENCIA) 
 values 
   ('1','Local');
Insert into LC_IEPFCMUP_PERTENENCIA 
   (ID_PERTENENCIA,DS_PERTENENCIA) 
 values 
   ('2','Comunidad Autónoma');
Insert into LC_IEPFCMUP_PERTENENCIA 
   (ID_PERTENENCIA,DS_PERTENENCIA) 
 values 
   ('3','Otros');