 CREATE TABLE "LC_INES_REGIMENPROTECCION" 
(	"ID_REGPROT" NUMBER(1,0) NOT NULL, 
	"DS_REGPROT" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_INES_REGIMENPROTECCION" PRIMARY KEY ("ID_REGPROT")
)
;

	/*Insert "LC_INES_REGIMENPROTECCION"*/
	
