CREATE TABLE "LC_IELIG_MEDIOMARINO" 
(	"CD_MEDIO_MARINO" NUMBER(2,0) NOT NULL, 
	"NB_MEDIO_MARINO" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_IELIG_MEDIOMARINO" PRIMARY KEY ("CD_MEDIO_MARINO")
)
;
   
   /*Insert "LC_IELIG_MEDIOMARINO"*/