CREATE TABLE "LC_IELIG_ESCALAVALORACION_02" 
(	"CD_VALORACION_02" NUMBER(1,0) NOT NULL, 
	"NB_VALORACION_02" VARCHAR2(50) NULL,
	CONSTRAINT "LC_IELIG_ESCALAVALORACION__PK" PRIMARY KEY ("CD_VALORACION_02")
)
;
   
   /*Insert "LC_IELIG_ESCALAVALORACION_02"*/