CREATE TABLE "LC_LUCDEME_RIESGODESER" 
(	"CD_RIESDESER" NUMBER(2,0) NOT NULL, 
	"DS_RIESDESER" VARCHAR2(100) NULL,
	CONSTRAINT "PK_LC_LUCDEME_RIESGODESER" PRIMARY KEY ("CD_RIESDESER")
)
;

	/*Insert "LC_LUCDEME_RIESGODESER"*/
	
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('1','BAJO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('2','MEDIO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('3','ALTO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('4','MUY ALTO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('8','LÁMINAS DE AGUA');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('9','URBANO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('99','FUERA DE PROGRAMA: Zonas húmedas y subhúmedas húmedas (Índice de aridez > 0,65)');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('1','BAJO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('2','MEDIO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('3','ALTO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('4','MUY ALTO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('8','LÁMINAS DE AGUA');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('9','URBANO');
Insert into LC_LUCDEME_RIESGODESER 
   (CD_RIESDESER,DS_RIESDESER) 
 values 
   ('99','FUERA DE PROGRAMA: Zonas húmedas y subhúmedas húmedas (Índice de aridez > 0,65)');
