CREATE TABLE "LC_LUCDEME_INCENDIOSFORESTALES" 
(	"CD_INCENDIOS" NUMBER(1,0) NOT NULL, 
	"DS_INCENDIOS" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_LUCDEME_INCENDIOSFOREST" PRIMARY KEY ("CD_INCENDIOS")
)
;

	/*Insert "LC_LUCDEME_INCENDIOSFORESTALES"*/

Insert into LC_LUCDEME_INCENDIOSFORESTALES 
   (CD_INCENDIOS,DS_INCENDIOS) 
 values 
   ('0','<10%');
Insert into LC_LUCDEME_INCENDIOSFORESTALES 
   (CD_INCENDIOS,DS_INCENDIOS) 
 values 
   ('1','>10%');
   
