CREATE TABLE "LC_RESEL_TESTADISTICO" 
(	"ID_TESTADISTICO" NUMBER(2) NOT NULL, 
	"DS_TESTADISTICO" VARCHAR2(150) NULL,
	CONSTRAINT "PK_LC_RESEL_TESTADISTICO" PRIMARY KEY ("ID_TESTADISTICO")
)
;

	/*Insert "LC_RESEL_TESTADISTICO"*/
	
Insert into LC_RESEL_TESTADISTICO 
   (ID_TESTADISTICO,DS_TESTADISTICO) 
 values 
   ('1',null);
Insert into LC_RESEL_TESTADISTICO 
   (ID_TESTADISTICO,DS_TESTADISTICO) 
 values 
   ('2','Excel');
Insert into LC_RESEL_TESTADISTICO 
   (ID_TESTADISTICO,DS_TESTADISTICO) 
 values 
   ('3','Excel y SPSS');
Insert into LC_RESEL_TESTADISTICO 
   (ID_TESTADISTICO,DS_TESTADISTICO) 
 values 
   ('4','Excel-Statistica');
Insert into LC_RESEL_TESTADISTICO 
   (ID_TESTADISTICO,DS_TESTADISTICO) 
 values 
   ('5','R');
Insert into LC_RESEL_TESTADISTICO 
   (ID_TESTADISTICO,DS_TESTADISTICO) 
 values 
   ('6','SPSS');
Insert into LC_RESEL_TESTADISTICO 
   (ID_TESTADISTICO,DS_TESTADISTICO) 
 values 
   ('7','Statistica');
Insert into LC_RESEL_TESTADISTICO 
   (ID_TESTADISTICO,DS_TESTADISTICO) 
 values 
   ('8','SYMPHONY');