CREATE TABLE "LC_RESEL_UINSTALADA" 
(	"ID_UINSTALADA" NUMBER(2) NOT NULL, 
	"DS_UINSTALADA" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_RESEL_UINSTALADA" PRIMARY KEY ("ID_UINSTALADA")
)
;

	/*Insert "LC_RESEL_UINSTALADA"*/
	
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('1',null);
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('2','1');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('3','117 sondas');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('4','118');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('5','12');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('6','16');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('7','17');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('8','2');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('9','211');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('10','3');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('11','3 y 3');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('12','36');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('13','4');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('14','4 sondas');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('15','6');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('16','7');
Insert into LC_RESEL_UINSTALADA 
   (ID_UINSTALADA,DS_UINSTALADA) 
 values 
   ('17','9');