CREATE TABLE "LC_RESEL_FALMACENAJE" 
(	"ID_FALMACENAJE" NUMBER(1) NOT NULL, 
	"DS_FALMACENAJE" VARCHAR2(20) NULL,
	CONSTRAINT "PK_LC_RESEL_FALMACENAJE" PRIMARY KEY ("ID_FALMACENAJE")
)
;

	/*Insert "LC_RESEL_FALMACENAJE"*/
	
Insert into LC_RESEL_FALMACENAJE 
   (ID_FALMACENAJE,DS_FALMACENAJE) 
 values 
   ('1',null);
Insert into LC_RESEL_FALMACENAJE 
   (ID_FALMACENAJE,DS_FALMACENAJE) 
 values 
   ('2','Acces');
Insert into LC_RESEL_FALMACENAJE 
   (ID_FALMACENAJE,DS_FALMACENAJE) 
 values 
   ('3','ASCII');
Insert into LC_RESEL_FALMACENAJE 
   (ID_FALMACENAJE,DS_FALMACENAJE) 
 values 
   ('4','Excel');
Insert into LC_RESEL_FALMACENAJE 
   (ID_FALMACENAJE,DS_FALMACENAJE) 
 values 
   ('5','Excel; Access; texto');