CREATE TABLE "LC_RESEL_EXPOSICION" 
(	"ID_EXPOSICION" NUMBER(2) NOT NULL, 
	"DS_EXPOSICION" VARCHAR2(10) NULL,
	CONSTRAINT "PK_LC_RESEL_EXPOSICION" PRIMARY KEY ("ID_EXPOSICION")
)
;

	/*Insert "LC_RESEL_EXPOSICION"*/
	
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('1',null);
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('2','E');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('3','E-NE');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('4','N');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('5','NE');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('6','NE-SW');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('7','N-NE');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('8','N-NW');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('9','NNW-SSE');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('10','N-S');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('11','NW');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('12','NW-SE');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('13','S');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('14','S-SE');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('15','S-SW');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('16','SW');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('17','SW-NE');
Insert into LC_RESEL_EXPOSICION 
   (ID_EXPOSICION,DS_EXPOSICION) 
 values 
   ('18','W');