CREATE TABLE "LC_RESEL_VDATALOGGER" 
(	"ID_VDATALOGGER" NUMBER(2) NOT NULL, 
	"DS_VDATALOGGER" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_RESEL_VDATALOGGER" PRIMARY KEY ("ID_VDATALOGGER")
)
;

	/*Insert "LC_RESEL_VDATALOGGER"*/
	
Insert into LC_RESEL_VDATALOGGER 
   (ID_VDATALOGGER,DS_VDATALOGGER) 
 values 
   ('1',null);
Insert into LC_RESEL_VDATALOGGER 
   (ID_VDATALOGGER,DS_VDATALOGGER) 
 values 
   ('2','Cada 15 dias');
Insert into LC_RESEL_VDATALOGGER 
   (ID_VDATALOGGER,DS_VDATALOGGER) 
 values 
   ('3','Cada 5 días');
Insert into LC_RESEL_VDATALOGGER 
   (ID_VDATALOGGER,DS_VDATALOGGER) 
 values 
   ('4','Cada evento');
Insert into LC_RESEL_VDATALOGGER 
   (ID_VDATALOGGER,DS_VDATALOGGER) 
 values 
   ('5','Cada mes');
Insert into LC_RESEL_VDATALOGGER 
   (ID_VDATALOGGER,DS_VDATALOGGER) 
 values 
   ('6','Cada semana');