CREATE TABLE "LC_RVP_DESCANSADERO" 
(	"ID_DESCANSADERO" NUMBER(2,0) NOT NULL, 
	"DS_DESCANSADERO" VARCHAR2(50) NULL,
	CONSTRAINT "PK_LC_RVP_DESCANSADERO" PRIMARY KEY ("ID_DESCANSADERO")
)
;

	/*Insert "LC_RVP_DESCANSADERO"*/
	
